[package]
name = "gyoma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.51.0"
imgui = "0.11.0"
sokol = { git = "https://github.com/floooh/sokol-rust", version = "0.1.0" }
